[project]
name = "motecloggenerator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "ldparser @ git+ssh://git@github.com/mathbrook/ldparser.git"
]
