name: Build Standalone Executable

on:
  push:
    tags:
      - '*'

jobs:
  build:
    continue-on-error: true
    name: Build Nuitka Executable
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: motec_log_gui-windows
            nuitka_py: .\\motec_log_gui.py

          - os: windows-11-arm
            artifact_name: motec_log_gui-arm-windows
            nuitka_py: .\\motec_log_gui.py

          - os: ubuntu-latest
            artifact_name: motec_log_gui-linux
            nuitka_py: ./motec_log_gui.py

          - os: macos-latest
            artifact_name: motec_log_gui-macos
            nuitka_py: ./motec_log_gui.py

          - os: ubuntu-24.04-arm
            artifact_name: motec_log_gui-arm-linux
            nuitka_py: ./motec_log_gui.py

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Sync dependencies with uv
        run: uv sync

      - name: Build standalone executable with Nuitka
        run: |
          uv run python -m nuitka --standalone ${{ matrix.nuitka_py }} --enable-plugin=tk-inter

      - name: Generate Release Notes
        id: release_notes
        run: |
          echo "# Release ${{ github.ref_name }}" > RELEASE_NOTES.md
          echo >> RELEASE_NOTES.md
          echo '## Changes since last release:' >> RELEASE_NOTES.md
          git log --pretty=format:'- %s (%an)' $(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))..HEAD >> RELEASE_NOTES.md

      - name: Upload Nuitka dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: motec_log_gui.dist/**

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: motec_log_gui.dist/**
          body_path: RELEASE_NOTES.md
